// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation AddLocationViewController
@end

@implementation LocationController
@end

@implementation LocationDetailViewController
@end

@implementation SearchableLocationTableViewController
@end

@implementation SelectLocationViewController
@end

@implementation SelectableRadiusMapViewController
@end

@implementation Annotation
@end

@implementation Location
@end

@implementation UIViewStyler
@end

@implementation ApplicationStylesheet
@end

@implementation LocationControllerStylesheet
@end

@implementation LocationTableViewCellStylesheet
@end

@implementation LocationTableViewCell
@end

